- platform: template
  sensors:
    office_1_occupied:
      friendly_name: "Office 1 - Occupied"
      value_template: >-
        {{ is_state("sensor.her_iphone_ra_room_presence", "Office 1")
            or is_state("sensor.his_ipone_ra_room_presence", "Office 1")
            or is_state("binary_sensor.living_room_motion_sensor_1_occupancy", "on")
            or is_state("binary_sensor.living_room_motion_sensor_2_occupancy", "on")
            or is_state("binary_sensor.living_room_motion_sensor_3_occupancy", "on")}}
