blueprint: 
  name: Auto Lighting - General Switch
  description: A script to toggle a input boolean switch and TTS to a speaker.
  domain: script
  source_url: https://github.com/eLVee1991/homeassistant/blob/main/blueprint_auto_lighting_general_switch.yaml
  input:
    entity_id:
      name: Speaker
      description: Speaker to send the tts to.
      default: ''
      selector:
        entity:
          domain: media_player
    switch:
      name: Input Boolean
      description: "Input boolean to toggle the auto lighting switch. You can create a toggle switch as a helper. For example: input_boolean.living_room_auto_lighting"
      default: ''
      selector:
        entity:
          domain: input_boolean
variables:
  entity_id: !input 'entity_id'
  switch: !input 'switch'
alias: Toggle - Input Boolean to TTS
sequence:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: '{{ entity_id }}'
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: '{{ switch }}'
  - service: tts.cloud_say
    data:
      entity_id: '{{ entity_id }}'
      message: |
        "{{ state_attr(switch, 'friendly_name') }}" is turned "{{ states(switch)
        }}"
description: A script to set the auto lighting switch to on/of and TTS to a speaker.
fields:
  entity_id:
    description: Speaker
    example: media_player.living_room_speaker
    required: true
  switch:
    description: Switch
    example: input_boolean.living_room_auto_lighting
    required: true
mode: single
