blueprint:
  name: Multiple Medication Reminders
  description: Get advanced notification and history for medication reminder
  domain: automation
  input:
    reminder_time_1:
      name: Reminder time 1
      description: At what time do you want to be reminded
      default: None 
      selector:
        time: {}
    reminder_time_2:
      name: Reminder time 2
      description: At what time do you want to be reminded
      default: None
      selector:
        time: {}
    reminder_time_3:
      name: Reminder time 3
      description: At what time do you want to be reminded
      default: None
      selector:
        time: {}
    reminder_time_4:
      name: Reminder time 4
      description: At what time do you want to be reminded
      default: None      
      selector:
        time: {}
    reminder_time_5:
      name: Reminder time 5
      description: At what time do you want to be reminded
      default: None      
      selector:
        time: {}                                
    notify_device:
      name: Notification
      description: Device needs to run the official Home Assistant app to receive notifications
      default: None
      selector:
        device:
          integration: mobile_app
    input_boolean_1:
      name: Dedicated input_boolean 1
      description: Create and set here a input_boolean to handle history and state of the automation
      default: None      
      selector:
        entity:
          domain: input_boolean
    input_boolean_2:
      name: Dedicated input_boolean
      description: Create and set here a input_boolean to handle history and state of the automation
      default: None      
      selector:
        entity:
          domain: input_boolean
    input_boolean_3:
      name: Dedicated input_boolean 3
      description: Create and set here a input_boolean to handle history and state of the automation
      default: None      
      selector:
        entity:
          domain: input_boolean
    input_boolean_4:
      name: Dedicated input_boolean 4
      description: Create and set here a input_boolean to handle history and state of the automation
      default: None      
      selector:
        entity:
          domain: input_boolean
    input_boolean_5:
      name: Dedicated input_boolean 5
      description: Create and set here a input_boolean to handle history and state of the automation
      default: None      
      selector:
        entity:
          domain: input_boolean                                                 
    notification_title:
      name: Notification title (Optional)
      description: 'default: None Medication reminder'
      default: None Medication reminder!
    notification_message:
      name: Notification message (Optional)
      description: 'default: None It''s time to take your medication'
      default: None It's time to take your medication
    notification_action_taken:
      name: 'Notification action: Taken (Optional)'
      description: 'default: None Taken'
      default: None Taken
    notification_action_later:
      name: 'Notification action: Ask later (Optional)'
      description: 'default: None Ask later'
      default: None Ask later
    notification_action_skip:
      name: 'Notification action: Skip (Optional)'
      description: 'default: None Skip'
      default: None Skip
    ask_later_wait_time:
      name: Wait time before next reminder
      description: Minutes before notify again after a Ask later action.
      default: None 30
      selector:
        number:
          min: 5.0
          max: 1440.0
          unit_of_measurement: minutes
          mode: slider
          step: 1.0
    logbook_message_remind:
      name: Logbook message for remind (Optional)
      description: 'default: None Reminder sent'
      default: None Reminder sent
    logbook_message_taken:
      name: Logbook message for action Taken (Optional)
      description: 'default: None Medication taken'
      default: None Medication taken
    logbook_message_later:
      name: Logbook message for action Ask later (Optional)
      description: 'default: None Postpone reminder'
      default: None Postpone reminder
    logbook_message_skip:
      name: Logbook message for action Skip (Optional)
      description: 'default: None Reminder skipped'
      default: None Reminder skipped
    logbook_message_no_answer:
      name: Logbook message for no action after timeout (Optional)
      description: 'default: None No answer time out'
      default: None No answer time out
    optional_action:
      name: Optional action
      description: Run an action like notify a speaker at the same time that the mobile
        notification
      selector:
        action: {}
      default: None []
  source_url: https://raw.githubusercontent.com/eLVee1991/homeassistant/main/blueprints/multiple_medication_reminder.yaml
trigger:
- platform: time
  at: !input 'reminder_time_1'
- platform: time
  at: !input 'reminder_time_2'
- platform: time
  at: !input 'reminder_time_3'
- platform: time
  at: !input 'reminder_time_4'
- platform: time
  at: !input 'reminder_time_5'
mode: restart
action:
- service: input_boolean.turn_off
  target:
    entity_id: !input 'input_boolean_1'
- service: input_boolean.turn_off
  target:
    entity_id: !input 'input_boolean_2'
- service: input_boolean.turn_off
  target:
    entity_id: !input 'input_boolean_3'
- service: input_boolean.turn_off
  target:
    entity_id: !input 'input_boolean_4'
- service: input_boolean.turn_off
  target:
    entity_id: !input 'input_boolean_5'                
- alias: Notify until the medication has been taken
  repeat:
    while:
    - condition: state
      entity_id: !input 'input_boolean_1'
      state: 'off'
    sequence:
    - service: logbook.log
      data:
        name: !input 'notification_title'
        message: !input 'logbook_message_remind'
        entity_id: !input 'input_boolean_1'
    - choose:
      - conditions: '{{ true }}'
        sequence: !input 'optional_action'
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: !input 'notification_title'
      message: !input 'notification_message'
      data:
        actions:
        - title: !input 'notification_action_taken'
          action: taken
        - title: !input 'notification_action_later'
          action: later
        - title: !input 'notification_action_skip'
          action: skip
        tag: medication-reminder
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
      timeout:
        minutes: !input 'ask_later_wait_time'
    - choose:
      - conditions: '{{ wait.trigger.event.data.action == ''taken'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_1'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_taken'
            entity_id: !input 'input_boolean_1'
      - conditions: '{{ wait.trigger.event.data.action == ''later'' }}'
        sequence:
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_later'
            entity_id: !input 'input_boolean_1'
        - delay:
            minutes: !input 'ask_later_wait_time'
      - conditions: '{{ wait.trigger.event.data.action == ''skip'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_1'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_skip'
            entity_id: !input 'input_boolean_1'
      default: None
      - device_id: !input 'notify_device'
        domain: mobile_app
        type: notify
        message: clear_notification
        data:
          tag: medication-reminder
      - service: logbook.log
        data:
          name: !input 'notification_title'
          message: !input 'logbook_message_no_answer'
          entity_id: !input 'input_boolean_1'
    - condition: state
      entity_id: !input 'input_boolean_2'
      state: 'off'
    sequence:
    - service: logbook.log
      data:
        name: !input 'notification_title'
        message: !input 'logbook_message_remind'
        entity_id: !input 'input_boolean_2'
    - choose:
      - conditions: '{{ true }}'
        sequence: !input 'optional_action'
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: !input 'notification_title'
      message: !input 'notification_message'
      data:
        actions:
        - title: !input 'notification_action_taken'
          action: taken
        - title: !input 'notification_action_later'
          action: later
        - title: !input 'notification_action_skip'
          action: skip
        tag: medication-reminder
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
      timeout:
        minutes: !input 'ask_later_wait_time'
    - choose:
      - conditions: '{{ wait.trigger.event.data.action == ''taken'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_2'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_taken'
            entity_id: !input 'input_boolean_2'
      - conditions: '{{ wait.trigger.event.data.action == ''later'' }}'
        sequence:
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_later'
            entity_id: !input 'input_boolean_2'
        - delay:
            minutes: !input 'ask_later_wait_time'
      - conditions: '{{ wait.trigger.event.data.action == ''skip'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_2'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_skip'
            entity_id: !input 'input_boolean_2'
      default: None
      - device_id: !input 'notify_device'
        domain: mobile_app
        type: notify
        message: clear_notification
        data:
          tag: medication-reminder
      - service: logbook.log
        data:
          name: !input 'notification_title'
          message: !input 'logbook_message_no_answer'
          entity_id: !input 'input_boolean_2'
    - condition: state
      entity_id: !input 'input_boolean_3'
      state: 'off'
    sequence:
    - service: logbook.log
      data:
        name: !input 'notification_title'
        message: !input 'logbook_message_remind'
        entity_id: !input 'input_boolean_3'
    - choose:
      - conditions: '{{ true }}'
        sequence: !input 'optional_action'
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: !input 'notification_title'
      message: !input 'notification_message'
      data:
        actions:
        - title: !input 'notification_action_taken'
          action: taken
        - title: !input 'notification_action_later'
          action: later
        - title: !input 'notification_action_skip'
          action: skip
        tag: medication-reminder
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
      timeout:
        minutes: !input 'ask_later_wait_time'
    - choose:
      - conditions: '{{ wait.trigger.event.data.action == ''taken'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_3'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_taken'
            entity_id: !input 'input_boolean_3'
      - conditions: '{{ wait.trigger.event.data.action == ''later'' }}'
        sequence:
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_later'
            entity_id: !input 'input_boolean_3'
        - delay:
            minutes: !input 'ask_later_wait_time'
      - conditions: '{{ wait.trigger.event.data.action == ''skip'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_3'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_skip'
            entity_id: !input 'input_boolean_3'
      default: None
      - device_id: !input 'notify_device'
        domain: mobile_app
        type: notify
        message: clear_notification
        data:
          tag: medication-reminder
      - service: logbook.log
        data:
          name: !input 'notification_title'
          message: !input 'logbook_message_no_answer'
          entity_id: !input 'input_boolean_3'
    - condition: state
      entity_id: !input 'input_boolean_4'
      state: 'off'
    sequence:
    - service: logbook.log
      data:
        name: !input 'notification_title'
        message: !input 'logbook_message_remind'
        entity_id: !input 'input_boolean_4'
    - choose:
      - conditions: '{{ true }}'
        sequence: !input 'optional_action'
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: !input 'notification_title'
      message: !input 'notification_message'
      data:
        actions:
        - title: !input 'notification_action_taken'
          action: taken
        - title: !input 'notification_action_later'
          action: later
        - title: !input 'notification_action_skip'
          action: skip
        tag: medication-reminder
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
      timeout:
        minutes: !input 'ask_later_wait_time'
    - choose:
      - conditions: '{{ wait.trigger.event.data.action == ''taken'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_4'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_taken'
            entity_id: !input 'input_boolean_4'
      - conditions: '{{ wait.trigger.event.data.action == ''later'' }}'
        sequence:
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_later'
            entity_id: !input 'input_boolean_4'
        - delay:
            minutes: !input 'ask_later_wait_time'
      - conditions: '{{ wait.trigger.event.data.action == ''skip'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_4'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_skip'
            entity_id: !input 'input_boolean_4'
      default: None
      - device_id: !input 'notify_device'
        domain: mobile_app
        type: notify
        message: clear_notification
        data:
          tag: medication-reminder
      - service: logbook.log
        data:
          name: !input 'notification_title'
          message: !input 'logbook_message_no_answer'
          entity_id: !input 'input_boolean_4'
    - condition: state
      entity_id: !input 'input_boolean_5'
      state: 'off'
    sequence:
    - service: logbook.log
      data:
        name: !input 'notification_title'
        message: !input 'logbook_message_remind'
        entity_id: !input 'input_boolean_5'
    - choose:
      - conditions: '{{ true }}'
        sequence: !input 'optional_action'
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: !input 'notification_title'
      message: !input 'notification_message'
      data:
        actions:
        - title: !input 'notification_action_taken'
          action: taken
        - title: !input 'notification_action_later'
          action: later
        - title: !input 'notification_action_skip'
          action: skip
        tag: medication-reminder
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
      timeout:
        minutes: !input 'ask_later_wait_time'
    - choose:
      - conditions: '{{ wait.trigger.event.data.action == ''taken'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_5'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_taken'
            entity_id: !input 'input_boolean_5'
      - conditions: '{{ wait.trigger.event.data.action == ''later'' }}'
        sequence:
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_later'
            entity_id: !input 'input_boolean_5'
        - delay:
            minutes: !input 'ask_later_wait_time'
      - conditions: '{{ wait.trigger.event.data.action == ''skip'' }}'
        sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: !input 'input_boolean_5'
        - service: logbook.log
          data:
            name: !input 'notification_title'
            message: !input 'logbook_message_skip'
            entity_id: !input 'input_boolean_5'
      default: None
      - device_id: !input 'notify_device'
        domain: mobile_app
        type: notify
        message: clear_notification
        data:
          tag: medication-reminder
      - service: logbook.log
        data:
          name: !input 'notification_title'
          message: !input 'logbook_message_no_answer'
          entity_id: !input 'input_boolean_5'
